# Generated by Django 3.1 on 2020-11-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizbox', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='ques_no',
            new_name='question',
        ),
        migrations.AddField(
            model_name='test',
            name='number_of_questions',
            field=models.IntegerField(default=84844),
            preserve_default=False,
        ),
    ]
