# Generated by Django 3.1 on 2020-11-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizbox', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='test_id',
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
