# Generated by Django 3.1 on 2020-11-05 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizbox', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='code',
            new_name='test_code',
        ),
    ]
