# Generated by Django 3.1 on 2020-11-02 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizbox', '0002_auto_20201101_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='test_id',
        ),
    ]
